import { createPublicClient, http, type PublicClient } from "viem";
import { activeNetwork, indexer } from "@/config";
import type { IndexerResponse } from "./client";

/**
 * ============================================================================
 * RPC-MODE INDEXER (A2, L1 port)
 * ============================================================================
 *
 * Drop-in replacement for the Conduit indexer on networks without one (Ethereum
 * Sepolia / local anvil): interprets the narrow SQL dialect produced by
 * queries.ts and answers it with plain `eth_getLogs` against the network RPC.
 *
 * WHY THIS SHAPE:
 * - Every query in queries.ts is a pure log filter (contract address + topic0 +
 *   optionally one indexed topic or an IN-list + block floor + order/limit).
 *   That maps 1:1 onto eth_getLogs — no joins, no aggregation, no derived state.
 * - Interpreting the existing SQL (rather than forking queries.ts) means the 13
 *   query functions, their decoding, and every consumer stay byte-identical, and
 *   event-history parity with eth_getLogs holds by construction (P1.M4 criterion).
 * - The dialect is generated by three known builders; anything unrecognized
 *   throws loudly rather than guessing.
 *
 * SCALE NOTE: ranges are scanned in chunks from the head backwards so DESC+LIMIT
 * queries stop early. Fine for the internal Sepolia volume; revisit for public
 * scale (the roadmap's indexer item) if ranges grow past ~1M blocks.
 * ============================================================================
 */

const CHUNK_BLOCKS = 45_000n; // under common public-RPC getLogs range caps

let _client: PublicClient | undefined;
function client(): PublicClient {
  if (!_client) {
    _client = createPublicClient({
      chain: activeNetwork,
      transport: http(activeNetwork.rpcUrls.default.http[0]),
    });
  }
  return _client;
}

interface ParsedQuery {
  selectAliases: { field: string; alias: string }[]; // field: 'topics[N]' | 'data' | meta
  address: `0x${string}`;
  topics: (`0x${string}` | `0x${string}`[] | null)[];
  fromBlock?: bigint;
  orderDesc: boolean;
  limit?: number;
}

/** Parse the fixed SELECT ... FROM logs WHERE ... template built by queries.ts. */
export function parseLogsQuery(query: string): ParsedQuery {
  const selectMatch = query.match(/SELECT\s+([\s\S]*?)\s+FROM\s+logs/i);
  const whereMatch = query.match(/WHERE([\s\S]*?)(ORDER BY|LIMIT|$)/i);
  if (!selectMatch || !whereMatch) {
    throw new Error(`[indexer/rpc] unrecognized query shape:\n${query}`);
  }

  const selectAliases = selectMatch[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => {
      const aliased = s.match(
        /^(topics\[\d\]|data|block_num|block_timestamp|tx_hash)(?:\s+as\s+(\w+))?$/i,
      );
      if (!aliased)
        throw new Error(`[indexer/rpc] unsupported SELECT field: ${s}`);
      return { field: aliased[1], alias: aliased[2] || aliased[1] };
    });

  const where = whereMatch[1];

  const addressMatch = where.match(/address\s*=\s*'(0x[0-9a-fA-F]{40})'/);
  if (!addressMatch)
    throw new Error("[indexer/rpc] query must filter by contract address");
  const address = addressMatch[1].toLowerCase() as `0x${string}`;

  // topics[N] = '0x...'  (SQL is 1-based: topics[1] is topic0)
  const topics: (`0x${string}` | `0x${string}`[] | null)[] = [
    null,
    null,
    null,
    null,
  ];
  for (const m of where.matchAll(/topics\[(\d)\]\s*=\s*'(0x[0-9a-fA-F]+)'/g)) {
    topics[Number(m[1]) - 1] = m[2].toLowerCase() as `0x${string}`;
  }
  // topics[N] IN ('0x..', '0x..')
  for (const m of where.matchAll(/topics\[(\d)\]\s+IN\s+\(([^)]*)\)/gi)) {
    const list = [...m[2].matchAll(/'(0x[0-9a-fA-F]+)'/g)].map(
      (x) => x[1].toLowerCase() as `0x${string}`,
    );
    topics[Number(m[1]) - 1] = list;
  }
  if (!topics[0])
    throw new Error(
      "[indexer/rpc] query must filter by topics[1] (event signature)",
    );

  const fromBlockMatch = where.match(/block_num\s*>=\s*(\d+)/);
  const orderMatch = query.match(/ORDER BY\s+block_num\s+(ASC|DESC)/i);
  const limitMatch = query.match(/LIMIT\s+(\d+)/i);

  // trim trailing wildcard topics (viem treats missing as wildcard)
  while (topics.length > 1 && topics[topics.length - 1] === null) topics.pop();

  return {
    selectAliases,
    address,
    topics,
    fromBlock: fromBlockMatch ? BigInt(fromBlockMatch[1]) : undefined,
    orderDesc: !orderMatch || orderMatch[1].toUpperCase() === "DESC",
    limit: limitMatch ? Number(limitMatch[1]) : undefined,
  };
}

/** Execute a parsed query via chunked eth_getLogs. */
export async function queryLogsViaRpc<T = any>(
  query: string,
): Promise<IndexerResponse<T>> {
  const q = parseLogsQuery(query);
  const c = client();

  const head = await c.getBlockNumber();
  const floor =
    q.fromBlock ?? BigInt(Math.max(0, indexer.deploymentBlock ?? 0));

  // Scan head->floor in chunks so DESC+LIMIT can stop early.
  // NOTE: raw eth_getLogs request — viem's getLogs() helper takes event/args and
  // silently drops a raw `topics` param, which would return unfiltered logs.
  const collected: any[] = [];
  let hi = head;
  while (hi >= floor) {
    const lo = hi - CHUNK_BLOCKS + 1n > floor ? hi - CHUNK_BLOCKS + 1n : floor;
    const raw = (await c.request({
      method: 'eth_getLogs',
      params: [
        {
          address: q.address,
          topics: q.topics,
          fromBlock: `0x${lo.toString(16)}`,
          toBlock: `0x${hi.toString(16)}`,
        },
      ],
    } as any)) as any[];
    const logs = raw.map((l) => ({
      data: l.data,
      topics: l.topics,
      blockNumber: BigInt(l.blockNumber),
      transactionHash: l.transactionHash,
    }));
    // within a chunk logs come ascending; collect respecting overall order
    collected.push(...(q.orderDesc ? logs.reverse() : logs));
    if (q.orderDesc && q.limit !== undefined && collected.length >= q.limit)
      break;
    if (lo === floor) break;
    hi = lo - 1n;
  }

  let ordered = collected;
  if (!q.orderDesc) {
    // chunks were gathered head-first; re-sort ascending
    ordered = [...collected].sort((a, b) =>
      Number(a.blockNumber - b.blockNumber),
    );
  }
  if (q.limit !== undefined) ordered = ordered.slice(0, q.limit);

  // block timestamps (Conduit rows carry block_timestamp; getLogs does not)
  const needTimestamps = q.selectAliases.some(
    (s) => s.field === "block_timestamp",
  );
  const tsByBlock = new Map<bigint, string>();
  if (needTimestamps) {
    const unique = [...new Set(ordered.map((l) => l.blockNumber as bigint))];
    await Promise.all(
      unique.map(async (bn) => {
        const block = await c.getBlock({ blockNumber: bn });
        tsByBlock.set(
          bn,
          new Date(Number(block.timestamp) * 1000).toISOString(),
        );
      }),
    );
  }

  const rows = ordered.map((log) => {
    const row: any = {};
    for (const { field, alias } of q.selectAliases) {
      if (field === "data") row[alias] = log.data;
      else if (field === "block_num") row[alias] = Number(log.blockNumber);
      else if (field === "block_timestamp")
        row[alias] = tsByBlock.get(log.blockNumber) ?? "";
      else if (field === "tx_hash") row[alias] = log.transactionHash;
      else {
        const idx = Number(field.match(/topics\[(\d)\]/)![1]) - 1; // SQL 1-based
        row[alias] = log.topics[idx] ?? "";
      }
    }
    return row;
  });

  return { data: rows as T[] };
}
