'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAppKitAccount } from '@reown/appkit/react';
import { Button } from '@/components/ui';
import { StakingForm } from '@/components/staking';
import { FundNodeForm } from '@/components/transfer';
import { toast } from 'sonner';
import { platforms } from '@/config';

type Platform = 'linux' | 'mac' | 'windows' | null;

export default function SetupPage() {
  const router = useRouter();
  const { isConnected } = useAppKitAccount();

  const [currentStep, setCurrentStep] = useState(1);
  const [platform, setPlatform] = useState<Platform>(null);
  const [publicKey, setPublicKey] = useState('');
  const [hasExistingStake, setHasExistingStake] = useState(false);
  const [hasExistingBalance, setHasExistingBalance] = useState(false);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success('Command copied to clipboard');
  };

  const handleStakingSuccess = async (
    operatorAddress: string,
    amount: string
  ) => {
    // Move to step 6 (fund node)
    setCurrentStep(6);
  };

  const handleFundingSuccess = async (nodeAddress: string, amount: string) => {
    // Move to step 7 (start node)
    setCurrentStep(7);
  };

  // Show multi-step setup with prototype design
  return (
    <div className="setup-page">
      <div
        className={`setup-page-gradient ${
          currentStep <= 3
            ? 'setup-page-gradient-top-right'
            : 'setup-page-gradient-bottom-left'
        }`}
      />

      <div className="setup-page-content">
        <div className="container">
          <div className="setup-grid">
            {/* Left: Bold title section */}
            <div className="setup-left">
              <h1 className="setup-heading">
                {currentStep === 1 && (
                  <>
                    Select
                    <br />
                    Platform
                  </>
                )}
                {currentStep === 2 && (
                  <>
                    Install
                    <br />
                    Docker
                  </>
                )}
                {currentStep === 3 && (
                  <>
                    Setup &amp; Run
                    <br />
                    Node
                  </>
                )}
                {currentStep === 4 && (
                  <>
                    Log Node's
                    <br />
                    Public Key
                  </>
                )}
                {currentStep === 5 && (
                  <>
                    Stake to
                    <br />
                    your node
                  </>
                )}
                {currentStep === 6 && (
                  <>
                    Fund Node
                    <br />
                    with ETH
                  </>
                )}
                {currentStep === 7 && (
                  <>
                    Start
                    <br />
                    Node
                  </>
                )}
              </h1>
              <p className="setup-description">
                {currentStep === 1 &&
                  'Choose your operating system for platform-specific setup instructions'}
                {currentStep === 2 &&
                  'Docker is required to run the Nillion verifier node'}
                {currentStep === 3 &&
                  'Pull the Docker image and run it to generate your node wallet'}
                {currentStep === 4 &&
                  'Enter the public key generated by your node'}
                {currentStep === 5 &&
                  'Stake TEST tokens to your node so it can be assigned verification work'}
                {currentStep === 6 &&
                  'Fund your node with ETH for gas transactions'}
                {currentStep === 7 &&
                  'Run the node binary to register and start your verifier node'}
              </p>
            </div>

            {/* Right: Floating glass card with form */}
            <div className="setup-right">
              {/* Step 1: Select Platform */}
              {currentStep === 1 && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 1 OF 7
                  </div>
                  <label className="setup-label">Select Platform</label>
                  <div className="setup-platform-grid">
                    {(Object.keys(platforms) as Array<keyof typeof platforms>).map((key) => (
                      <button
                        key={key}
                        onClick={() => setPlatform(key)}
                        className={`setup-platform-button ${
                          platform === key ? 'selected' : ''
                        }`}
                      >
                        {platforms[key].displayName}
                      </button>
                    ))}
                  </div>

                  <Button
                    variant="outline"
                    size="large"
                    onClick={() => setCurrentStep(2)}
                    disabled={!platform}
                    className="setup-button-full"
                  >
                    Continue
                  </Button>
                </div>
              )}

              {/* Step 2: Install Docker */}
              {currentStep === 2 && platform && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 2 OF 7
                  </div>
                  <label className="setup-label">Install Docker</label>

                  {platform === 'windows' ? (
                    <div className="setup-download-card">
                      <div className="setup-download-info">
                        <h3 className="setup-download-filename">
                          Docker Desktop
                        </h3>
                        <p className="setup-download-description">
                          Download and install Docker Desktop for Windows
                        </p>
                      </div>

                      <Button
                        variant="primary"
                        size="large"
                        className="setup-button-full"
                        onClick={() => {
                          window.open(
                            platforms[platform].dockerInstallUrl,
                            '_blank'
                          );
                        }}
                      >
                        Download Docker Desktop
                      </Button>
                    </div>
                  ) : (
                    <div>
                      <div
                        style={{
                          display: 'flex',
                          gap: '0.75rem',
                          marginBottom: '1rem',
                          alignItems: 'flex-start',
                        }}
                      >
                        <div
                          style={{
                            flex: 1,
                            background: 'rgba(0, 0, 0, 0.5)',
                            border: '1px solid rgba(255, 255, 255, 0.1)',
                            borderRadius: '0.75rem',
                            padding: '1.25rem',
                            fontFamily: 'monospace',
                            fontSize: '0.875rem',
                            color: 'var(--nillion-primary-lighter)',
                            wordBreak: 'break-all',
                            minWidth: 0,
                          }}
                        >
                          {platforms[platform].dockerInstallCommand}
                        </div>
                        <button
                          onClick={() =>
                            handleCopy(platforms[platform].dockerInstallCommand!)
                          }
                          style={{
                            background: 'rgba(255, 255, 255, 0.1)',
                            border: 'none',
                            padding: '0.5rem 1rem',
                            borderRadius: '0.375rem',
                            color: 'rgba(255, 255, 255, 0.6)',
                            cursor: 'pointer',
                            whiteSpace: 'nowrap',
                            flexShrink: 0,
                          }}
                        >
                          Copy
                        </button>
                      </div>
                      {platform === 'mac' && (
                        <p className="setup-note" style={{ marginTop: '0.5rem' }}>
                          Alternatively, you can{' '}
                          <a
                            href={platforms[platform].dockerInstallUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{ color: 'var(--nillion-primary)' }}
                          >
                            download Docker Desktop
                          </a>{' '}
                          instead.
                        </p>
                      )}
                    </div>
                  )}

                  <p className="setup-note">
                    <strong>Note:</strong> Docker is required to run the Nillion verifier node.
                    After installation, you may need to restart your terminal.
                  </p>

                  <div className="setup-button-group">
                    <Button variant="ghost" onClick={() => setCurrentStep(1)}>
                      Back
                    </Button>
                    <Button
                      variant="outline"
                      size="large"
                      onClick={() => setCurrentStep(3)}
                      className="setup-button-compact"
                    >
                      I've Installed Docker
                    </Button>
                  </div>
                </div>
              )}

              {/* Step 3: Pull & Run Docker Image */}
              {currentStep === 3 && platform && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 3 OF 7
                  </div>
                  <label className="setup-label">Pull Docker Image</label>
                  <div
                    style={{
                      display: 'flex',
                      gap: '0.75rem',
                      marginBottom: '1.5rem',
                      alignItems: 'flex-start',
                    }}
                  >
                    <div
                      style={{
                        flex: 1,
                        background: 'rgba(0, 0, 0, 0.5)',
                        border: '1px solid rgba(255, 255, 255, 0.1)',
                        borderRadius: '0.75rem',
                        padding: '1.25rem',
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                        color: 'var(--nillion-primary-lighter)',
                        wordBreak: 'break-all',
                        minWidth: 0,
                      }}
                    >
                      {platforms[platform].dockerPullCommand}
                    </div>
                    <button
                      onClick={() => handleCopy(platforms[platform].dockerPullCommand)}
                      style={{
                        background: 'rgba(255, 255, 255, 0.1)',
                        border: 'none',
                        padding: '0.5rem 1rem',
                        borderRadius: '0.375rem',
                        color: 'rgba(255, 255, 255, 0.6)',
                        cursor: 'pointer',
                        whiteSpace: 'nowrap',
                        flexShrink: 0,
                      }}
                    >
                      Copy
                    </button>
                  </div>

                  <label className="setup-label">Run Node Setup</label>
                  <div
                    style={{
                      display: 'flex',
                      gap: '0.75rem',
                      marginBottom: '1rem',
                      alignItems: 'flex-start',
                    }}
                  >
                    <div
                      style={{
                        flex: 1,
                        background: 'rgba(0, 0, 0, 0.5)',
                        border: '1px solid rgba(255, 255, 255, 0.1)',
                        borderRadius: '0.75rem',
                        padding: '1.25rem',
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                        color: 'var(--nillion-primary-lighter)',
                        wordBreak: 'break-all',
                        minWidth: 0,
                      }}
                    >
                      {platforms[platform].dockerRunCommand}
                    </div>
                    <button
                      onClick={() => handleCopy(platforms[platform].dockerRunCommand)}
                      style={{
                        background: 'rgba(255, 255, 255, 0.1)',
                        border: 'none',
                        padding: '0.5rem 1rem',
                        borderRadius: '0.375rem',
                        color: 'rgba(255, 255, 255, 0.6)',
                        cursor: 'pointer',
                        whiteSpace: 'nowrap',
                        flexShrink: 0,
                      }}
                    >
                      Copy
                    </button>
                  </div>

                  <p className="setup-note">
                    <strong>Note:</strong> On first run, the node will generate a new wallet and save it to <code>./nilav_node/nilav_node.env</code>.
                    Your wallet address will be displayed - you'll need this for the next step.
                  </p>

                  <div className="setup-button-group">
                    <Button variant="ghost" onClick={() => setCurrentStep(2)}>
                      Back
                    </Button>
                    <Button
                      variant="outline"
                      size="large"
                      onClick={() => setCurrentStep(4)}
                      className="setup-button-compact"
                    >
                      I've Run It
                    </Button>
                  </div>
                </div>
              )}

              {/* Step 4: Enter Public Key */}
              {currentStep === 4 && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 4 OF 7
                  </div>
                  <label className="setup-label">Enter Node's Public Key</label>
                  <input
                    type="text"
                    value={publicKey}
                    onChange={(e) => setPublicKey(e.target.value)}
                    placeholder="0x..."
                    className="setup-input"
                  />

                  <p className="setup-note">
                    <strong>Note:</strong> This is the public key (address) that
                    your node generated. You'll stake to this address in the
                    next step.
                  </p>

                  <div className="setup-button-group">
                    <Button variant="ghost" onClick={() => setCurrentStep(3)}>
                      Back
                    </Button>
                    <Button
                      variant="primary"
                      size="large"
                      disabled={!publicKey || publicKey.length < 12}
                      onClick={() => setCurrentStep(5)}
                      className="setup-button-compact"
                    >
                      Continue
                    </Button>
                  </div>
                </div>
              )}

              {/* Step 5: Stake to Node */}
              {currentStep === 5 && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 5 OF 7
                  </div>

                  <StakingForm
                    nodePublicKey={publicKey}
                    onSuccess={handleStakingSuccess}
                    onError={(error) => {
                      console.error('Staking failed:', error);
                    }}
                    onStakeDataChange={(data) => {
                      setHasExistingStake(data.currentStake > 0);
                    }}
                  />

                  <div
                    className="setup-button-group"
                    style={{ marginTop: '1.5rem' }}
                  >
                    <Button variant="ghost" onClick={() => setCurrentStep(4)}>
                      Back
                    </Button>
                    {isConnected && hasExistingStake && (
                      <Button
                        variant="outline"
                        size="large"
                        onClick={() => setCurrentStep(6)}
                        className="setup-button-compact"
                      >
                        Continue
                      </Button>
                    )}
                  </div>
                </div>
              )}

              {/* Step 6: Fund Node with ETH */}
              {currentStep === 6 && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 6 OF 7
                  </div>

                  <FundNodeForm
                    nodePublicKey={publicKey}
                    onSuccess={handleFundingSuccess}
                    onError={(error) => {
                      console.error('Funding failed:', error);
                    }}
                    onBalanceDataChange={(data) => {
                      setHasExistingBalance(data.nodeBalance > 0);
                    }}
                  />

                  <div
                    className="setup-button-group"
                    style={{ marginTop: '1.5rem' }}
                  >
                    <Button variant="ghost" onClick={() => setCurrentStep(5)}>
                      Back
                    </Button>
                    {isConnected && hasExistingBalance && (
                      <Button
                        variant="outline"
                        size="large"
                        onClick={() => setCurrentStep(7)}
                        className="setup-button-compact"
                      >
                        Continue
                      </Button>
                    )}
                  </div>
                </div>
              )}

              {/* Step 7: Start Node */}
              {currentStep === 7 && platform && (
                <div>
                  <div className="setup-step-indicator">
                    <div className="setup-step-line" />
                    STEP 7 OF 7
                  </div>
                  <label className="setup-label">Run this command</label>
                  <div
                    style={{
                      display: 'flex',
                      gap: '0.75rem',
                      marginBottom: '1rem',
                      alignItems: 'flex-start',
                    }}
                  >
                    <div
                      style={{
                        flex: 1,
                        background: 'rgba(0, 0, 0, 0.5)',
                        border: '1px solid rgba(255, 255, 255, 0.1)',
                        borderRadius: '0.75rem',
                        padding: '1.25rem',
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                        color: 'var(--nillion-primary-lighter)',
                        wordBreak: 'break-all',
                        minWidth: 0,
                      }}
                    >
                      {platforms[platform].nodeStartCommand}
                    </div>
                    <button
                      onClick={() => {
                        handleCopy(platforms[platform].nodeStartCommand);
                      }}
                      style={{
                        background: 'rgba(255, 255, 255, 0.1)',
                        border: 'none',
                        padding: '0.5rem 1rem',
                        borderRadius: '0.375rem',
                        color: 'rgba(255, 255, 255, 0.6)',
                        cursor: 'pointer',
                        whiteSpace: 'nowrap',
                        flexShrink: 0,
                      }}
                    >
                      Copy
                    </button>
                  </div>

                  <p className="setup-note">
                    After running this command, you should see "Node registered
                    successfully" in your terminal. This means your node is
                    successfully running and ready to receive verification work.
                  </p>

                  <div className="setup-button-group">
                    <Button variant="ghost" onClick={() => setCurrentStep(6)}>
                      Back
                    </Button>
                    <Button
                      variant="ghost"
                      size="large"
                      onClick={() => {
                        window.open('https://discord.gg/nillion', '_blank');
                      }}
                      className="setup-button-compact"
                    >
                      Help
                    </Button>
                    <Button
                      variant="primary"
                      size="large"
                      onClick={() => {
                        // Show success message
                        toast.success(
                          `Node setup complete! Your node is now running.`
                        );

                        // Redirect to node detail page
                        router.push(`/nodes/${publicKey}`);
                      }}
                      className="setup-button-compact"
                    >
                      I see it
                    </Button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
